#!/data/data/com.termux/files/usr/bin/bash
# desktop.sh — Termux:X11 + XFCE running INSIDE the Ubuntu container, with a
# GPU acceleration pipeline.
#
# Lessons from this device (Redmi Note 13 Pro 5G, SD 7s Gen 2 / Adreno 710),
# all baked in:
#   * the session script must NOT live at rootfs/tmp — --shared-tmp binds
#     Termux's $PREFIX/tmp OVER the container's /tmp, shadowing it (use /opt)
#   * proot-distro --detach reads the command as a FILE argument, never stdin
#   * the X server runs under app_process: kill it with pkill -f, not pkill
#   * xfwm4 compositing = black desktop / vanishing panel on Termux:X11: off
#   * a stale dbus-daemon exports dead socket addresses ("Unable to contact
#     settings server") — stale buses are killed with the session
#   * GPU: Turnip does not support Adreno 710 (documented exception), so the
#     acceleration path here is VirGL (virgl_test_server_android in Termux +
#     GALLIUM_DRIVER=virpipe in the container), with llvmpipe fallback.
#     Turnip/Zink can be tried per-app later — see README "GPU acceleration".
set -Eeuo pipefail

log()  { printf '\033[1;32m==>\033[0m %s\n' "$*"; }
warn() { printf '\033[1;33mWARN:\033[0m %s\n' "$*" >&2; }
die()  { printf '\033[1;31mERROR:\033[0m %s\n' "$*" >&2; exit 1; }

CONTAINER="${PD_CONTAINER_NAME:-ubuntu}"
UBU_USER="${PD_UBUNTU_USER:-thalha}"
DISPLAY_NUM="${PD_DISPLAY:-:1}"
X11_ARGS="${PD_X11_ARGS:-}"
GPU_MODE="${PD_GPU:-auto}"            # auto | virgl | llvmpipe
ROOTFS="$PREFIX/var/lib/proot-distro/containers/$CONTAINER/rootfs"

[ -n "${TERMUX_VERSION:-}" ] || die "Run this inside Termux."
[ -d "$ROOTFS" ] || die "Container '$CONTAINER' not found — run scripts/setup-ubuntu.sh first."
[ -x "$ROOTFS/usr/bin/startxfce4" ] || \
  die "XFCE not installed in the container — run scripts/install-desktop.sh first."
command -v termux-x11 >/dev/null 2>&1 || die "termux-x11 missing — run scripts/install-x11.sh first."

if ! grep -q "^${UBU_USER}:" "$ROOTFS/etc/passwd" 2>/dev/null; then
  warn "User '$UBU_USER' not found in the container — launching as root."
  UBU_USER="root"
fi

# ── 1. clean slate ──────────────────────────────────────────────────────────
log "Stopping stale X server / desktop / dbus..."
pkill -f termux-x11 2>/dev/null || true
pkill -f 'startxfce4|xfce4-session|xfwm4|xfdesktop|xfce4-panel|xfsettingsd|xfconfd' 2>/dev/null || true
pkill -f 'virgl_test_server' 2>/dev/null || true
pkill -f dbus-daemon 2>/dev/null || true
proot-distro kill "$CONTAINER" 2>/dev/null || true
sleep 1

# ── 2. GPU acceleration (VirGL proxy, llvmpipe fallback) ───────────────────
GPU_ENV=""
gpu_note="llvmpipe (software rendering)"
if [ "$GPU_MODE" != "llvmpipe" ]; then
  if command -v virgl_test_server_android >/dev/null 2>&1; then
    log "Starting VirGL GPU proxy server (Termux side)..."
    virgl_test_server_android >"$HOME/.cache/virgl.log" 2>&1 &
    sleep 2
    if pgrep -f virgl_test_server >/dev/null 2>&1; then
      GPU_ENV="GALLIUM_DRIVER=virpipe MESA_GL_VERSION_OVERRIDE=4.3COMPAT MESA_GLES_VERSION_OVERRIDE=3.2 vblank_mode=0"
      gpu_note="virgl (GPU-accelerated via Android GL)"
      log "VirGL server is up — container apps will use $gpu_note"
    else
      warn "VirGL server failed to start (see ~/.cache/virgl.log) — falling back to llvmpipe."
    fi
  else
    warn "virgl_test_server_android not installed — run scripts/install-x11.sh (or pkg install virglrenderer-android)."
  fi
fi
[ -n "$GPU_ENV" ] || GPU_ENV="LIBGL_ALWAYS_SOFTWARE=1 vblank_mode=0"

# ── 3. X server ─────────────────────────────────────────────────────────────
log "Starting Termux:X11 on display ${DISPLAY_NUM}..."
# $X11_ARGS is intentionally unquoted: it may hold multiple flags
# shellcheck disable=SC2086
termux-x11 "$DISPLAY_NUM" $X11_ARGS >"$HOME/.cache/termux-x11.log" 2>&1 &
sleep 3

log "Opening the Termux:X11 activity on the phone..."
am start --user 0 -n com.termux.x11/com.termux.x11.MainActivity >/dev/null 2>&1 || \
  warn "Could not auto-open the app — tap the Termux:X11 icon on your launcher."

# ── 4. session orchestrator (inside the container, /opt — never /tmp!) ─────
# Firefox needs a real /dev/shm for tab IPC — bind a Termux-side dir over it
# (Android has no /dev/shm of its own) and disable Firefox sandboxes that
# cannot exist under proot (seccomp-based), or tabs crash on signal 11.
mkdir -p "$PREFIX/tmp/xd-shm"; chmod 777 "$PREFIX/tmp/xd-shm"

log "Writing session orchestrator into the container..."
SESSION_SH="$ROOTFS/opt/xd-session.sh"
rm -f "$ROOTFS/opt/xd-session.log"
cat > "$SESSION_SH" <<EOF
#!/bin/bash
# generated by scripts/desktop.sh — runs INSIDE the container
set -u
exec >>/opt/xd-session.log 2>&1
echo "=== xd-session start: \$(date) user=\$(id -un) display=${DISPLAY_NUM} ==="

export DISPLAY="${DISPLAY_NUM}"
export XDG_RUNTIME_DIR="\$HOME/.cache/xdg-runtime"
mkdir -p "\$XDG_RUNTIME_DIR"; chmod 700 "\$XDG_RUNTIME_DIR"
export GDK_BACKEND=x11
# GPU mode chosen on the Termux side (virpipe = VirGL proxy, or llvmpipe):
export ${GPU_ENV}
# Firefox under proot: /dev/shm is bind-mounted from Termux (see desktop.sh);
# the seccomp content sandbox cannot work under proot and crashes tabs.
export MOZ_DISABLE_CONTENT_SANDBOX=1
export MOZ_DISABLE_RDD_SANDBOX=1
export MOZ_DISABLE_GPU_SANDBOX=1

# wait until the X server accepts connections (max ~40 s)
if command -v xdpyinfo >/dev/null 2>&1; then
  i=0; until xdpyinfo >/dev/null 2>&1; do
    i=\$((i+1)); [ \$i -ge 40 ] && break; sleep 1
  done
  echo "x server reachable after \${i}s"
else
  echo "xdpyinfo not installed — sleeping 10 s instead"
  sleep 10
fi

# compositing under Termux:X11 = black desktop / missing panel; keep it off
# (must run inside the dbus session so xfconfd is reachable)

echo "starting XFCE..."
exec dbus-launch --exit-with-session bash -c '
  xfconf-query -c xfwm4 -p /general/use_compositing --create -t bool -s false >/dev/null 2>&1 || true
  echo "compositor disabled; session env: ${GPU_ENV}"
  exec startxfce4
'
EOF
chmod 755 "$SESSION_SH"

log "Launching the desktop inside the container as '${UBU_USER}' (GPU: ${gpu_note})..."
proot-distro login "$CONTAINER" --user "$UBU_USER" \
  --bind "$PREFIX/tmp/xd-shm:/dev/shm" \
  --shared-tmp --shared-x11 --detach -- \
  /bin/bash /opt/xd-session.sh

# ── 5. liveness + panel wait ────────────────────────────────────────────────
started=0
for _ in $(seq 1 15); do
  [ -s "$ROOTFS/opt/xd-session.log" ] && { started=1; break; }
  sleep 1
done
[ "$started" = 1 ] || die "session never started (no log). Debug it live:
  proot-distro login $CONTAINER --user $UBU_USER --shared-tmp --shared-x11 -- /bin/bash /opt/xd-session.sh"

log "Waiting for XFCE to come up (max 60 s)..."
up=0
for _ in $(seq 1 60); do
  if pgrep -f 'xfce4-session' >/dev/null 2>&1 && pgrep -f 'xfwm4' >/dev/null 2>&1; then up=1; break; fi
  sleep 1
done

if [ "$up" = 1 ]; then
  log "XFCE is up (GPU: ${gpu_note}). Check the Termux:X11 app."
else
  warn "session not detected after 60 s — last log lines:"
  tail -20 "$ROOTFS/opt/xd-session.log" || true
fi

cat <<EOF

Desktop running. Useful:
  tail -40 $ROOTFS/opt/xd-session.log   # container session log
  proot-distro kill ${CONTAINER} && pkill -f termux-x11   # stop everything
  bash scripts/desktop.sh               # restart

Black screen?  PD_X11_ARGS="-legacy-drawing" bash scripts/desktop.sh
No GPU?       PD_GPU=llvmpipe bash scripts/desktop.sh   (default: PD_GPU=auto)
GL check:     bash scripts/container-app.sh glxgears
Benchmark:    bash scripts/container-app.sh glmark2
EOF
