#!/data/data/com.termux/files/usr/bin/bash
# desktop.sh — launch Termux:X11 + an XFCE session inside the Ubuntu container.
#
# Flow:
#   1. start the X server on the Termux side (background)
#   2. open the Termux:X11 activity on the phone
#   3. run a session orchestrator inside the container (detached) that:
#        - exports a sane session env (XDG_RUNTIME_DIR, software GL)
#        - disables xfwm4 compositing (the #1 cause of black desktops and
#          vanishing panels on Termux:X11)
#        - starts XFCE once the X server is reachable
#        - nudges xfdesktop/xfce4-panel to repaint a few times (first-draw
#          race: without this the desktop can stay black until a manual
#          `xfdesktop --reload`)
#
# Stop it: expand the Termux:X11 notification -> Exit, then:
#   pkill termux-x11 && proot-distro kill "$PD_CONTAINER_NAME"
set -Eeuo pipefail

log()  { printf '\033[1;32m==>\033[0m %s\n' "$*"; }
warn() { printf '\033[1;33mWARN:\033[0m %s\n' "$*" >&2; }
die()  { printf '\033[1;31mERROR:\033[0m %s\n' "$*" >&2; exit 1; }

CONTAINER="${PD_CONTAINER_NAME:-ubuntu}"
UBU_USER="${PD_UBUNTU_USER:-thalha}"
DISPLAY_NUM="${PD_DISPLAY:-:1}"
X11_ARGS="${PD_X11_ARGS:-}"
ROOTFS="$PREFIX/var/lib/proot-distro/containers/$CONTAINER/rootfs"

[ -n "${TERMUX_VERSION:-}" ] || die "Run this inside Termux."
[ -d "$ROOTFS" ] || die "Container '$CONTAINER' not found — run scripts/setup-ubuntu.sh first."
[ -x "$ROOTFS/usr/bin/startxfce4" ] || \
  die "XFCE not installed in the container — run scripts/install-desktop.sh first."
command -v termux-x11 >/dev/null 2>&1 || die "termux-x11 missing — run scripts/install-x11.sh first."

# Fall back to root only if the user was never created in this container.
if ! grep -q "^${UBU_USER}:" "$ROOTFS/etc/passwd" 2>/dev/null; then
  warn "User '$UBU_USER' not found in the container — launching as root."
  warn "(Re-run scripts/setup-ubuntu.sh to create it, or set PD_UBUNTU_USER.)"
  UBU_USER="root"
fi

log "Stopping any stale X server / container sessions..."
pkill termux-x11 2>/dev/null || true
sleep 1
proot-distro kill "$CONTAINER" 2>/dev/null || true

log "Starting Termux:X11 server on display ${DISPLAY_NUM}..."
# $X11_ARGS is intentionally unquoted: it may hold multiple flags
# shellcheck disable=SC2086
termux-x11 "$DISPLAY_NUM" $X11_ARGS >/dev/null 2>&1 &
sleep 4

log "Opening the Termux:X11 activity on the phone..."
am start --user 0 -n com.termux.x11/com.termux.x11.MainActivity >/dev/null 2>&1 || \
  warn "Could not auto-open the app — tap the Termux:X11 icon on your launcher."

log "Writing session orchestrator into the container..."
SESSION_SH="$ROOTFS/tmp/xd-session.sh"
rm -f "$ROOTFS/tmp/xd-session.log"
cat > "$SESSION_SH" <<EOF
#!/bin/bash
# generated by scripts/desktop.sh — runs INSIDE the container
set -u
exec >>/tmp/xd-session.log 2>&1
echo "=== xd-session start: \$(date) user=\$(id -un) display=${DISPLAY_NUM} ==="

export DISPLAY="${DISPLAY_NUM}"
export XDG_RUNTIME_DIR="\$HOME/.cache/xdg-runtime"
mkdir -p "\$XDG_RUNTIME_DIR"; chmod 700 "\$XDG_RUNTIME_DIR"
# deterministic GL under proot: no hardware paths that silently fail
export LIBGL_ALWAYS_SOFTWARE=1
export GDK_BACKEND=x11

# wait until the X server accepts connections (max ~40 s)
if command -v xdpyinfo >/dev/null 2>&1; then
  i=0; until xdpyinfo >/dev/null 2>&1; do
    i=\$((i+1)); [ \$i -ge 40 ] && break; sleep 1
  done
  echo "x server reachable after \${i}s"
else
  echo "xdpyinfo not installed — sleeping 10 s instead"
  sleep 10
fi

# repaint nudges: the first draw can land before the phone surface is ready
(
  for w in 5 8 12; do
    sleep "\$w"
    xfdesktop --reload >/dev/null 2>&1 || (nohup xfdesktop >/dev/null 2>&1 &)
    xfce4-panel -r   >/dev/null 2>&1 || true
    echo "repaint nudge done (+\${w}s)"
  done
) &

# compositing under Termux:X11 = black desktop / missing panel; keep it off
xfconf-query -c xfwm4 -p /general/use_compositing --create -t bool -s false >/dev/null 2>&1 || true

echo "starting XFCE..."
exec dbus-launch --exit-with-session bash -c 'exec startxfce4'
EOF
chmod 755 "$SESSION_SH"

log "Launching the session inside the container as '${UBU_USER}' (detached)..."
proot-distro login "$CONTAINER" --user "$UBU_USER" --shared-tmp --shared-x11 --detach -- \
  /bin/bash /tmp/xd-session.sh

cat <<EOF

XFCE is starting. Give it ~15 s on first draw (the orchestrator repaints a
few times; the desktop may flash once — that's the nudge working).

Useful:
  proot-distro ps                      # see running container sessions
  proot-distro kill ${CONTAINER}       # stop the desktop session
  pkill termux-x11                     # stop the X server
  Restart anytime: bash scripts/desktop.sh

Still black?  Read the session log and send it:
  cat $PREFIX/var/lib/proot-distro/containers/${CONTAINER}/rootfs/tmp/xd-session.log
Or:  PD_X11_ARGS="-legacy-drawing" bash scripts/desktop.sh
Swapped colours?  PD_X11_ARGS="-force-bgra" bash scripts/desktop.sh
Fonts huge?  add '-dpi 120' via PD_X11_ARGS, or XFCE Appearance -> DPI.
EOF
